//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events2._0.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Core.Mapping;
    using System.Drawing;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Windows;

    public partial class Events
    {
        public int Number { get; set; }
        public string Events1 { get; set; }
        public string DATE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public Nullable<int> CITY { get; set; }

        public virtual City City1 { get; set; }

        public Color Background  { get { return Color.White; } }


        public string ImgPath 
        {
            get
            {
                var path = "/Resources/" + this.Number + ".jpg";
                    return path;
            }
        }

       
    }
}
