//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events2._0.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jury
    {
        public int id_Jury { get; set; }
        public string Sec { get; set; }
        public string Fisrt { get; set; }
        public string Patr { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string DoB { get; set; }
        public Nullable<int> Country { get; set; }
        public string Phone { get; set; }
        public string Act { get; set; }
        public string Pass { get; set; }
        public string Foto { get; set; }
    
        public virtual Country Country1 { get; set; }
    }
}
