//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events2._0.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class организаторы
    {
        public int id_organizators { get; set; }
        public string Firstname { get; set; }
        public string Secondname { get; set; }
        public string Patronymic { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> Date_of_birthday { get; set; }
        public Nullable<int> Country { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public string Gender { get; set; }
    
        public virtual Country Country1 { get; set; }
    }
}
